apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: vicenct-dev
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: <REEMPLAZAR>
  MYSQL_DATABASE: gam
  MYSQL_USER: metabase
  MYSQL_PASSWORD: <REEMPLAZAR>
  MB_DB_TYPE: mysql
  MB_DB_HOST: mysql-service
  MB_DB_PORT: "3306"
  MB_DB_DBNAME: metabase_db
  MB_DB_USER: app_user
  MB_DB_PASS: <REEMPLAZAR>
  MB_ADD_SAMPLE_DATASET: "false"
  MB_ADMIN_FIRST_NAME: Admin
  MB_ADMIN_LAST_NAME: Sistema
  MB_ADMIN_EMAIL: admin@proyecto.com
  MB_ADMIN_PASSWORD: <REEMPLAZAR>
  MB_SITE_NAME: Dashboard de Movilidad
